name = "wanderealty"
compatibility_date = "2026-03-17"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[vars]
NEXT_PUBLIC_SANITY_PROJECT_ID = "p0v1013t"
NEXT_PUBLIC_SANITY_DATASET = "production"
